import { z } from "zod";
import { convertToEnum, designation, gender } from "./z.schema.types";
const genderEnum = convertToEnum(gender, "gender");
type gender = z.infer<typeof genderEnum>;
const designationEnum = convertToEnum(designation, "designation");
type designation = z.infer<typeof designationEnum>;

export type UserData = {
  id?: number;
  firstname: string;
  middlename?: string | null;
  lastname: string;
  email: string;
  phone: string;
  address: string;
  dateOfBirth: Date | number | string;
  gender: gender;
  designation: designation;
  emergencyContactNumber: string;
  emergencyContactName: string;
  joindate: Date | string | number;
  enddate: string;
  height: number;
  weight: number;
  hips: number;
  chest: number;
  waist: number;
  thigh: number;
  allergies: string;
  medicalCondition: string;
  bloodGroup: string;
  paymentStatus: string;
  streak?: number;
  profile: string;
  lastAttendance?: Date | null;
};
